/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetRouteImport } from './routes/pet'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadTokenRouteImport } from './routes/download.$token'
import { Route as ApiPurchaseRouteImport } from './routes/api.purchase'

const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTokenRoute = DownloadTokenRouteImport.update({
  id: '/download/$token',
  path: '/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchaseRoute = ApiPurchaseRouteImport.update({
  id: '/api/purchase',
  path: '/api/purchase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/desktop': typeof DesktopRoute
  '/pet': typeof PetRoute
  '/api/purchase': typeof ApiPurchaseRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/desktop': typeof DesktopRoute
  '/pet': typeof PetRoute
  '/api/purchase': typeof ApiPurchaseRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/desktop': typeof DesktopRoute
  '/pet': typeof PetRoute
  '/api/purchase': typeof ApiPurchaseRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy'
    | '/desktop'
    | '/pet'
    | '/api/purchase'
    | '/download/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buy' | '/desktop' | '/pet' | '/api/purchase' | '/download/$token'
  id:
    | '__root__'
    | '/'
    | '/buy'
    | '/desktop'
    | '/pet'
    | '/api/purchase'
    | '/download/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  DesktopRoute: typeof DesktopRoute
  PetRoute: typeof PetRoute
  ApiPurchaseRoute: typeof ApiPurchaseRoute
  DownloadTokenRoute: typeof DownloadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$token': {
      id: '/download/$token'
      path: '/download/$token'
      fullPath: '/download/$token'
      preLoaderRoute: typeof DownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchase': {
      id: '/api/purchase'
      path: '/api/purchase'
      fullPath: '/api/purchase'
      preLoaderRoute: typeof ApiPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  DesktopRoute: DesktopRoute,
  PetRoute: PetRoute,
  ApiPurchaseRoute: ApiPurchaseRoute,
  DownloadTokenRoute: DownloadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
